### ISSUE TITLE
YAML config

### ISSUE THREAD

**Issue by RickyCook** [aelsabbahy/goss#13]
There are a number of advantages to using YAML instead of JSON as your config file:
- superset of JSON, so nothing breaks
- nice things like references to other places in the YAML
- much nicer to read (see the example below)
- allows comments

**YAML** (auto generated)
```yaml
command:
  redis-cli info:
    exit-status: '0'
    stdout: [redis_version]
file:
  /etc/redis.conf:
    contains: [bind 0.0.0.0]
    exists: true
    filetype: file
package:
  redis: {installed: true}
port:
  tcp:6379: {ip: 0.0.0.0, listening: true}
service:
  redis: {running: true}
```

**JSON**
```json
{
    "package": {
        "redis": {
            "installed": true
        }
    },
    "file": {
        "/etc/redis.conf": {
            "exists": true,
            "filetype": "file",
            "contains": ["bind 0.0.0.0"]
        }
    },
    "port": {
        "tcp:6379": {
            "listening": true,
            "ip": "0.0.0.0"
        }
    },
    "service": {
        "redis": {
            "running": true
        }
    },
    "command": {
        "redis-cli info": {
            "exit-status": "0",
            "stdout": ["redis_version"]
        }
    }
}
```

**Comment by aelsabbahy** [comment]
YAML support would be nice. The only concern is comments. They would disapear when a `goss add...` is run. Would that be an issue?

**Comment by RickyCook** [comment]
Yeah that's true. That would be a problem. Not sure how to solve that one!

**Comment by mtpereira** [comment]
Hello!

What if the resource blocks had support for a `name` or `comment` field, similar to the `name` field on Ansbile tasks? It would be optional and, to avoid disrupting the current structure, would be bellow the actual resource name. For example:

```
command:
  name: Check that redis-cli info is available and executing ok
  redis-cli info:
    exit-status: '0'
    stdout: [redis_version]
```

This would pretty much kill the need for comments on this files, which I believe is a good workaroud and compromise.

**Comment by aelsabbahy** [comment]
@mtpereira That sounds great! I assume `name` would be nested under the redis-cli object? right?:

```yaml
---
command:
  redis-cli info:
    name: Check that redis-cli info is available and executing ok
    exit-status: '0'
    stdout: [redis_version]
```
