### ISSUE TITLE
JUnit format show stdout/stderr

### ISSUE THREAD

**Issue by santiagax99** [aelsabbahy/goss#167]
Will be great to see actual stdout/stderr in JUnit formatter from "command" check if we testing stdout/stderr pattern 

goss.yaml:
```
command:
    check-package.py:
        exit-status: 0
        stdout:
        - "Missing: []"
        - "Conflicts: []"
```

here is current result (v0.2.4)
```
<testcase name="Command check-package.py exit-status" time="0.421">
<system-err>
Command: check-package.py: exit-status: doesn't match, expect: [0] found: [1]
</system-err>
<failure>
Command: check-package.py: exit-status: doesn't match, expect: [0] found: [1]
</failure>
</testcase>
<testcase name="Command check-package.py stdout" time="0.000">
<system-err>
Command: check-package.py: stdout: patterns not found: [Missing: [], Conflicts: []]
</system-err>
<failure>
Command: check-package.py: stdout: patterns not found: [Missing: [], Conflicts: []]
</failure>
</testcase>
```
and command run result
```
$ check-package.py
Satisfied: []
Conflicts: ['argparse<=1.3.1,>=1.2.0']
Missing: []
```
for exit-status goss returns actual exit-code - "found: [1]", but stdout not.

**Comment by mkobit** [comment]
I was just going to file an issue for this.

```
✗ build/bin/goss --version                                         
goss version v0.3.6
```

`goss_example.yaml`
```yaml
command:
  echo 'hello world:
    exit-status: 0
    stdout:
      - 'Hello World'
```

Using all of the formats, I was unable to get an output report that captured the stdout/stderr of a failed test.
