### ISSUE TITLE
Binary symlink incorrectly detects exit code, stdout, stderr

### ISSUE THREAD

**Issue by bryanlatten** [aelsabbahy/goss#171]
Test set up:

```
root@b3c84a501150:/# ls -l /usr/sbin/binary-symlink
lrwxrwxrwx 1 root root 20 Nov 10 21:38 /usr/sbin/binary-symlink -> /usr/sbin/binary
```

Test intentionally failed `binary` for good exit code:

```
command: 
    binary:
      exit-status: 0
      stdout: [0]
```

Running tests:

```
root@b3c84a501150:/# goss -g /tests/goss.yaml validate
....................................F..........

Failures/Skipped:

Testing `binary` for exit status of 0 (fails)

Command: binary: exit-status:
Expected
    <int>: 0
to equal
    <int>: 1

Total Duration: 0.297s
Count: 47, Failed: 1, Skipped: 0
```

Testing `binary-symlink` for same exit code

```
command: 
    binary-symlink:
      exit-status: 0
      stdout: [0]
```

```
root@b3c84a501150:/# goss -g /tests/goss-symlink.yaml validate
..............................................

Total Duration: 0.279s
Count: 46, Failed: 0, Skipped: 0
```

And it passes, unfortunately.
