### ISSUE TITLE
Better handling of parser errors

### ISSUE THREAD

**Issue by velenux** [aelsabbahy/goss#173]
I was testing goss with a few regular expression checks for content inside a file:

```yaml
file:
  /etc/hosts:
    exists: true
    contains:
    - "!/::1[[:space:]]+localhost\./"
```

The regexp was making the YAML parser fail and it took me a while to find out why, the error message was just **"Unable to determine format from content"**.

I'm not entirely sure this is working as intended, but it turns out I had to use a double backslash (`\\`) to escape the `.`. A better error message (maybe report which line/character fails) would have helped a lot :)

I'm no programmer, but I could try to put in a pull request to clarify this in the documentation if you want.
