### ISSUE TITLE
port vs.expose

### ISSUE THREAD

**Issue by gimler** [aelsabbahy/goss#177]
When using docker-compose i would check if a container has a specific port exposed.

```
version: '2'
services:
  service:
    ...
    expose:
      - "9000"
```

this doesn't work
```
port:
  tcp:9000:
    listening: true
    ip:
    - 0.0.0.0
```

output
```
.......FS.................

Failures/Skipped:

Port: tcp:9000: listening:
Expected
    <bool>: false
to equal
    <bool>: true
Port: tcp:9000: ip: skipped

Total Duration: 0.101s
Count: 26, Failed: 1, Skipped: 1
```

netstat -lnt
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.11:35818        0.0.0.0:*               LISTEN      
tcp        0      0 :::9000                 :::*                    LISTEN
```

**Comment by aelsabbahy** [comment]
Try tcp6, I think this is related to #149

**Comment by gimler** [comment]
this works as expected 

```
port:
  tcp6:9000:
    listening: true
    ip:
    - '::'
```
