### ISSUE TITLE
Add generic description to tests

### ISSUE THREAD

**Issue by oldNoakes** [aelsabbahy/goss#181]
Would like to be able to document the test I am running to give those that come behind me some context as to why that test exists.  

Here is a limited example of some of our current tests:

```
command:
  su - jenkins -c 'bundler --version':
    exit-status: 0
  ruby -e "require 'nokogiri'; puts Nokogiri::VERSION":
    exit-status: 0
    stdout:
      - /[\d\.]+/
```

The issue I am trying to fix is that no one on my team necessarily knows *why* I have ensured that the jenkins user can use bundler but that the root user has nokogiri available to them.  I can put in comments into the goss file itself but having the ability to describe the test more than just its results would be fantastic.

I see the field being optional and the input being something like this:

```
command:
  su - jenkins -c 'bundler --version':
    exit-status: 0
  ruby -e "require 'nokogiri'; puts Nokogiri::VERSION":
    description: Verify root user has Nokogiri gem - required for userdata in EC2 startup
    exit-status: 0
    stdout:
      - /[\d\.]+/
```
Am trying to sort out how it could be incorporated into the output from the tests in a useful manner seeing as it is an optional field.
