### ISSUE TITLE
Help with gomega matchers

### ISSUE THREAD

**Issue by tfhartmann** [aelsabbahy/goss#182]
Hi there, I was wondering of someone could help me understand how the gomega matchers work. I'd like to create a test to validate the major and minor release of a package, and ignore the patch release.  It looked like gomega matcher were the way to use the match-regexp matcher, I get an error that I'm not understanding. 

so this works

```Yaml
package:
  tomcat7:
    installed: true
    versions:
      and:
        - contain-element: "7.0.73"
```

However this test  returns an error. 

```Yaml
package:
  tomcat7:
    installed: true
    versions:
      and:
        - match-regexp: "7.0.73"
```

which returns this error

```
tomcat7: version: Error: RegExp matcher requires a string or stringer.
Got:    <[]string | len:1, cap:1>: ["7.0.73"]
```

It looks to me like i'm passing the value of match-regexp wrong, but for the life of me, I can't seem to figure out how to pass it correctly.  Any help would be awesome! 

Thanks!

**Comment by aelsabbahy** [comment]
`match-regexp` works on strings, not arrays.
https://onsi.github.io/gomega/#working-with-strings-json-and-yaml
`contain-element` works on "collections", and can take another gomega matcher as the "test"
https://onsi.github.io/gomega/#containelementelement-interface

So you want something like this:
```yaml
package:
  tomcat7:
    installed: true
    versions:
      contain-element:
        match-regexp: "7.0.73-some-regexp"
    # OR if you need multiple tests with `and`
    versions:
      and:
        - contain-element:
            match-regexp: "some-regex"
        - some-other-matcher: ...
```

Let me know if that helps.
