### ISSUE TITLE
Determine Presence of SSH Authorized Key

### ISSUE THREAD

**Issue by naftulikay** [aelsabbahy/goss#189]
I'd like to use Goss to validate that a given user has a given SSH authorized key or set of keys. It should be pretty trivial to examine `~/.ssh/authorized_keys` and validate that a given key or key fingerprint exists.

**Comment by aelsabbahy** [comment]
Unless I'm misunderstanding, this should be easy to accomplish with a simple file check.

Example goss.yaml:
```yaml
file:
  ~/.ssh/authorized_keys:
    exists: true
    contains:
      - "key1..."
      - "key2..."
```
