### ISSUE TITLE
Symlink Exists gives the status of target file rather than the symlink file

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#193]
**Setup:**
```
ln -s /tmp/does_not_exist /tmp/foo
```

goss.yml
```
file:
  /tmp/foo:
    exists: true
    filetype: symlink
```

```
$ goss validate
FS

Failures/Skipped:

File: /tmp/foo: exists:
Expected
    <bool>: false
to equal
    <bool>: true
File: /tmp/foo: filetype: skipped

Total Duration: 0.001s
Count: 2, Failed: 1, Skipped: 1
```

I would expect that test to pass
