### ISSUE TITLE
Add description for fail

### ISSUE THREAD

**Issue by marcinpraczko** [aelsabbahy/goss#230]
Would be nice to have description for fail. Most of my experience with verification is that shows something (OK/FAIL) but not clear info how to fix issue when fails.

For example, lets say that there is complex provisioning and one tests fail.
```bash
...
Failures/Skipped:

File: /etc/passwd: contains: patterns not found: [aloof]
HINT: Please visit http://some_url/CM-1000
```

And this could looks in code like this
```yaml
file:
  /etc/passwd:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains:
      - aloof
    fail_hint: Please visit http://some_url/CM-1000
```

From my point of view this is really missing in all verification. Easy HINT for 'potential' action how to fix issue. On this URL - http://some_url/CM-1000 - can be clear info what should be run to (re-run CM, manual command, etc).
