### ISSUE TITLE
Not able to use vars

### ISSUE THREAD

**Issue by adeleglise** [aelsabbahy/goss#239]
Hi,

Maybe (and even probably) I don't know how to properly use the vars file.

I'm trying to build a vars.yaml containing the IP adress of the network interfaces to test :

```yaml
interface:
  - eth0
  addrs:
    - 192.168.60.211/24
```

```yaml
interface:
{{range .Vars.interface}}:
{{.}}:
  addrs:
    - {{.}}
{{end}}
```

I've tried many syntax and ordering, but the tests wont run ...

Could you please give me an help in hand ?
