### ISSUE TITLE
Add description for documentation output

### ISSUE THREAD

**Issue by erichs** [aelsabbahy/goss#241]
Similar in nature to #230, it would be great if we could add descriptive metadata to tests that explain why the test is there. This can be accomplished in the YAML file themselves via comments, of course, but it would be nice to have an output mode, like `-f documentation`, that renders these back out as strings, like:

```
[vagrant@host ~]$ goss v -f documentation
File: /etc/passwd: exists: matches expectation: [true], satisfies PCI requirement 8
File: /etc/passwd: mode: matches expectation: ["0644"], satisfies PCI requirement 8
File: /etc/passwd: owner: matches expectation: ["root"], satisfies PCI requirement 8
File: /etc/passwd: group: matches expectation: ["root"], satisfies PCI requirement 8
File: /etc/passwd: filetype: matches expectation: ["file"], satisfies PCI requirement 8
File: /etc/passwd: size: matches expectation: [1130], satisfies PCI requirement 8
```

given an optional parameter like:

```yaml
file:
  /etc/passwd:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains:
      - aloof
    documentation: satisfies PCI requirement 8
```

This output, normally supressed, would be useful to show an auditor, say, of the system.

If a PR implementing the above would be likely to be approved, I'd welcome pointers or suggestions on how best to implement it. I'm fairly new to golang.

**Comment by pysysops** [comment]
Hey! Interestingly I thought about this earlier today too. I'm attempting to build the config for goss to validate servers to CIS benchmarks and thought it'd be cool to reference them in a comments or documentation field.

I guess we'd only want the output on certain formats  like documentation, JSON and nagios_verbose?

**Comment by pysysops** [comment]
Ahmed is usually open to pull requests and new functions that add value not complexity. As a new golang user myself I've found his feedback really helpful even when what I'd done was perhaps not ideal. 

My advice is to fork it, branch it, code it, and document it and open a PR. Just be open to the possibility that initially your implementation might need some reworking. I've opened plenty of PRs and then killed them because they werent great. There isn't a great deal of unit testing in this project the tests are more functional / integration focused.

**Comment by aelsabbahy** [comment]
Does the current `title` and `meta` not meet your needs? [manually editing goss files](https://github.com/aelsabbahy/goss#manually-editing-goss-files) Seems I need to add this features documentation to the main manual, it appears to only be in the readme.

```yaml
user:
  root:
    title: ensure root user exists
    meta:
      hint.1: ctrl-alt-delete
      hint.2: Hold power button
      hint.3: Re-install your OS
      hint.4: Cry
      id: code-1234
      severity: 5
    exists: true
```

Output:
```
$ goss validate --format documentation
Title: ensure root user exists
Meta:
    hint.1: ctrl-alt-delete
    hint.2: Hold power button
    hint.3: Re-install your OS
    hint.4: Cry
    id: code-1234
    severity: 5
User: root: exists: matches expectation: [true]


Total Duration: 0.000s
Count: 1, Failed: 0, Skipped: 0
```
