### ISSUE TITLE
Can't figure out why cURL fails

### ISSUE THREAD

**Issue by fracasula** [aelsabbahy/goss#261]
Hi guys,

I'm having some issues with a long cURL command. Unfortunately goss just says `patterns not found` but since it does not print any output I'm unable to figure this out.
The cURL command works when launched manually from within the container so I must be doing something wrong in the regex to check `stdout` or maybe when I escape the cURL command itself (even though it seems a valid yaml file to me and phpstorm :thinking: ).

Here's my `goss.yaml` file:

```yml
port:
    tcp6:8000:
        listening: true
        ip: ['::']

command:
    "curl localhost:8000":
        title: Checking main entrypoint
        exit-status: 0
        stdout:
            - "Empty body"
        stderr: []
        timeout: 1000
    "curl -i -H \"Content-Type: application/json\" -X POST -d @./build/fixtures/example.com.1.json localhost:8000":
        title: Checking script + xpath on example.com
        exit-status: 0
        stdout:
            - "200 OK"
        stderr: []
        timeout: 10000
```

The first two tests are passing, the last one fails. Here's the output I get when I run the command manually:

```
$ curl -i -H "Content-Type: application/json" -X POST -d @./build/fixtures/example.com.1.json localhost:8000
HTTP/1.1 200 OK
Content-type: application/json
Date: Mon, 10 Jul 2017 09:15:57 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"scripts":[{"result":{"type":"string","value":"This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission."}}],"xpaths":[{"outerHTML":"More information..."}],"responses":[{"requestId":"208.1","timestamp":3229.716217,"type":"Document","url":"http://example.com/","status":200,"statusText":"OK","mimeType":"text/html","headers":{"Date":"Mon, 10 Jul 2017 09:15:57 GMT","Content-Encoding":"gzip","Last-Modified":"Fri, 09 Aug 2013 23:54:35 GMT","Server":"ECS (iad/182A)","Etag":"\"359670651+gzip\"","Vary":"Accept-Encoding","X-Cache":"HIT","Content-Type":"text/html","Cache-Control":"max-age=604800","Accept-Ranges":"bytes","Content-Length":"606","Expires":"Mon, 17 Jul 2017 09:15:57 GMT"}}]}
```

I also tried to change the `stdout` pattern to `HTTP/1.1 200 OK` but it didn't work.

Thanks in advance for any help :+1:
