### ISSUE TITLE
Validate compressed file content

### ISSUE THREAD

**Issue by bamarni** [aelsabbahy/goss#264]
My use case is with linux ikconfig, I'd like to assert some kernel build configs inside `/proc/config.gz`.

I could be doing it with command validation and zgrep, but it can quickly become too verbose, imo that could be nice to have it builtin with the file validation. Would such feature be acceptable for goss?

**Comment by aelsabbahy** [comment]
Hmm.. would using the `command` validator with `zcat /proc/config.gz` be a viable option, should give you very similar checks to the file one.

**Comment by bamarni** [comment]
I hadn't see that we could assert on command output. Sorry, I don't have a setup to test, but would it work with multiple lines? eg : 

```yaml
command:
  zcat /proc/config.gz:
    exit-status: 0
    stdout:
      - CONFIG_A=y
      - CONFIG_B=m
```

If that's the case your solution seems nice, then feel free to close and thank you!
