### ISSUE TITLE
Allow multiple elements for the same definition

### ISSUE THREAD

**Issue by rgarrigue** [aelsabbahy/goss#286]
Hello

My goss yaml looks like

```
file:
  /etc/yum.repos.d/epel-testing.repo:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
  /etc/yum.repos.d/epel.repo:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file

# and ~10 others files with the same attributes but different path
```

I wish I could write something like this, like switch case in some language defaulting to next values if no break;

```
file:
  /etc/yum.repos.d/epel-testing.repo:
  /etc/yum.repos.d/epel.repo:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
```

Or maybe a comma separated list of file

```
file:
  /etc/yum.repos.d/epel-testing.repo, /etc/yum.repos.d/epel.repo:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
```

Or a regexpr

```
file:
  /etc/yum.repos.d/{epel,epel-testing}.repo:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
```

Or a path attribute with list which would overide a dumb label. Maybe that'ld the best way to do it, since you could easily template this

```
file:
  dumb_label:
    path:
      - /etc/yum.repos.d/epel-testing.repo
      - /etc/yum.repos.d/epel.repo
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
```

Best regards,
