### ISSUE TITLE
Yaml lint compliancy

### ISSUE THREAD

**Issue by rgarrigue** [aelsabbahy/goss#289]
Hey

I was working on testing my ansible role via Molecule and Goss as a verifier, which made me realize goss.yaml file aren't compliant with `yamllint`

```
[root@d34608241828 ~]# goss aa bash
Adding Package to './goss.yaml':

bash:
  installed: true
  versions:
  - 4.2.46


Adding Process to './goss.yaml':

bash:
  running: true


[root@d34608241828 ~]# yamllint goss.yaml
goss.yaml
  1:1       warning  missing document start "---"  (document-start)
  5:5       error    wrong indentation: expected 6 but found 4  (indentation)
```

Here's the correct formating : add --- and indent list items

```
---
package:
  bash:
    installed: true
    versions:
      - 4.2.46
process:
  bash:
    running: true
```

Best regards
