### ISSUE TITLE
Why dgoss java test fails

### ISSUE THREAD

**Issue by kameshsampath** [aelsabbahy/goss#297]
Hi,

I wrote a very simple dgoss test to test the JDK version of the docker image I have built.

from my container `java -version` returns

```
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```
I am trying to have simple command check 

`goss.yml`

```
package:
  java-1.8.0-openjdk:
    installed: true
    versions:
      - 1.8.0.144
command:
  java -version:
    exit-status: 0
    stdout:
      - 1.8.0_144
    stderr: []
    timeout: 1000
```

The package test passes with version while the java -version fails saying its not able to find the string 1.8.0_144, as noticed from the java command above the 1.8.0_144 is available as part of stdout.

`test.sh`

```
#!/bin/bash

set -e

docker pull registry.centos.org/che-stacks/centos-jdk8:latest || exit 1

i=0
time dgoss run registry.centos.org/che-stacks/centos-jdk8:latest || ((i++))

exit $i
```
