### ISSUE TITLE
Add verification for redirect

### ISSUE THREAD

**Issue by marcinpraczko** [aelsabbahy/goss#299]
In ``http`` module there are details about status, but I am not see whether there is a way of checking if redirection is valid.

For example
```yaml
http:
  http://some.domain.here:
    status: 301
    no-follow-redirects: true
```

Expected to setup something like that (for example):
```yaml
http:
  http://some.domain.here:
    status: 301
    no-follow-redirects: true
    headers:
      - 'Location https://some.another.domain.here'
```

This will allow faster and quicker check if redirects are valid.
