### ISSUE TITLE
Glob/Regex support for file names

### ISSUE THREAD

**Issue by Chumper** [aelsabbahy/goss#308]
In our container we create directories with the tier in the name, e.g. `service-dev-ue1`, because we create jenkins jobs and want to verify the job has been created.

It would be great if the file resource would support glob like patterns for the name of the file.
Something like this:

```
file:
- name: "/tmp/jenkins/jobs/service-.*-.*"
  exists: true
  mode: "0755"
  size: 4096
  owner: jenkins
  group: jenkins
  filetype: directory
  contains: []
```

Would also be great to have the possibillity of using environment variables inside the yaml so we can even be more specific:
```
file:
- name: "/tmp/jenkins/jobs/service-{{TIER}}-{{REGION}}"
  exists: true
  mode: "0755"
  size: 4096
  owner: jenkins
  group: jenkins
  filetype: directory
  contains: []
```
