### ISSUE TITLE
How to check obligatory 'port' from the 'range'

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#311]
Hi,

Some services like '[glusterfs](https://www.gluster.org/)' has ability to listen on the next port from the range if the previous port is occupied already. Like "base-port" can be 24009, while since it is a port bigger then 1024 at can be already occupied by some other service, in this case glusterfs chooses the next port 24010 (or 24011 if 24010 is in use, etc and so on until it reached the allowed range/retries).

So far it is impossible to check the port by goss there, like:
```
port:
  # glusterfs
  tcp:24009:
    listening: true
    ip: ["x.x.x.x"]
```

Any there any possibility to improve the 'port' check to have ability to check the range?
Something like:
```
port:
  # glusterfs
  tcp:24009-24019:
    listening: true
    count: 1
    process: glusterfs
    ip: ["x.x.x.x"]
```

In this case we will be sure _one_ glusterfs process is available within the specified port range.
Low priority here, while nice-2-have feature, IMHO. Just willing to hear your vision here. Tnx!

P.S. Happy New Year!
