### ISSUE TITLE
Bug: HTTP check fails when http content is too large with 'body' attribute

### ISSUE THREAD

**Issue by evancarter-iex** [aelsabbahy/goss#315]
If you have something like this:
```
http:
  http://api.magicthegathering.io/v1/cards?page=311:
    # required attributes
    status: 200
    timeout: 1000
    body: [colors] # Check http response content for these patterns
```
Goss will return:

``` Body: Error: bufio.Scanner: token too long```

and thus "failing"
