### ISSUE TITLE
dgoss running process check fails whereas goss pass due to SystemV/Systemd setup

### ISSUE THREAD

**Issue by JackLeo** [aelsabbahy/goss#323]
I am using rabbitmq so have a test:

```yaml
package:
  rabbitmq-server:
    installed: true
    versions:
    - 3.5.0n

process:
  rabbitmq-server:
    running: true
```

This works a charm on Centos7. Now I want to run the same tests on Docker to validate the automation.
In Docker container from `centos:7` this does fail with the process not running.

Now the reason as far as I understand is that `rabbitmq-server`, when launched through System V script, is more detectable.

Centos7:
```
ps aux | grep rabbitmq-server
root      1173  0.0  0.1 115512  1068 ?        S    09:35   0:00 /bin/sh /etc/rc.d/init.d/rabbitmq-server start
root      1175  0.0  0.1 115244  1480 ?        S    09:35   0:00 /bin/bash -c ulimit -S -c 0 >/dev/null 2>&1 ; /usr/sbin/rabbitmq-server
root      1179  0.0  0.2 187668  2404 ?        S    09:35   0:00 su rabbitmq -s /bin/sh -c /usr/lib/rabbitmq/bin/rabbitmq-server
```

Docker centos:7:
```
root         1  0.0  0.0  79812  3868 ?        Ss   16:41   0:00 su rabbitmq -s /bin/sh -c /usr/lib/rabbitmq/bin/rabbitmq-server
```

So because it is wrapped in `su rabbitmq -s /bin/sh -c` a test for process running sh does work.
