### ISSUE TITLE
dgoss to ignore service enabled

### ISSUE THREAD

**Issue by JackLeo** [aelsabbahy/goss#324]
As commented in https://github.com/aelsabbahy/goss/issues/323 I am running the same test suite against a container as well as the docker image to validate the automation and reduce the feedback cycle.

I am running these tests:
```yaml
package:
  rabbitmq-server:
    installed: true
    versions:
    - 3.5.0n

service:
  rabbitmq-server:
    enabled: true
    running: true
```

So this fails with

```
Failures/Skipped:

Service: rabbitmq-server: enabled:
Expected
    <bool>: false
to equal
    <bool>: true
```

Whereas passing test:
```yaml
service:
  rabbitmq-server:
    enabled: false
    running: true
```

So since docker does not have dbus running, test for service running I assume is skipped, but enabled cannot be tested thus fails.
