### ISSUE TITLE
Process module: validate that a process is running under a user account

### ISSUE THREAD

**Issue by chbndrhnns** [aelsabbahy/goss#338]
I would like to validate that some application is not running as root. Is there currently a way to check this? Otherwise I suggest extending the process module:

```
process:
  chrome:
    # required attributes
    running: true
    # optional attributes
    user: root
```
