### ISSUE TITLE
Test case splitting

### ISSUE THREAD

**Issue by daswars** [aelsabbahy/goss#339]
Hello, I have the following situation.
I would like to write a CIS benchmark based on goss (http://obmyaeceh.bkt.clouddn.com/CIS_CentOS_Linux_7_Benchmark_v2.1.0.pdf)

How can I split a test?
In my example, only the last exam took poured.

```
cat goss.yaml
gossfile:
  /etc/goss.d/*.yaml: {}
```

```
cat /etc/goss.d/cis-1.1.2.yaml
mount:
  /tmp:
    exists: true
    title: 1.1.2 Ensure separate partition exists for /tmp
    meta:
      desc: The /tmpdirectory is a world-writable directory used for temporary storage by all users and some applications.
      scored: true
      lvl-server: 2
      lvl-desktop: 2
```

```
cat /etc/goss.d/cis-1.1.3.yaml
mount:
  /tmp:
    exists: true
    opts:
    - nodev
    title: 1.1.3 Ensure separate partition exists for /tmp
    meta:
      desc: The nodevmount option specifies that the filesystem cannot contain special devices.
      scored: true
      lvl-server: 1
      lvl-desktop: 1
```

```
cat /etc/goss.d/cis-1.1.4.yaml
mount:
  /tmp:
    exists: true
    opts:
    - noexec
    title: 1.1.4 Ensure separate partition exists for /tmp
    meta:
      desc: The nosuidmount option specifies that the filesystem cannot contain setuid files.
      scored: true
      lvl-server: 1
      lvl-desktop: 1
```

Result looks like this:
```
goss validate -f tap
1..2
ok 1 - Mount: /tmp: exists: matches expectation: [true]
ok 2 - Mount: /tmp: opts: matches expectation: [["noexec"]]
```

So only cis-1.1.4.yaml is tested here
Is there a solution for the following situation?

Thanks Freddy
