### ISSUE TITLE
Add feature for checking php ini values

### ISSUE THREAD

**Issue by catdevman** [aelsabbahy/goss#341]
@aelsabbahy I believe that the [php_config serverspec resource](http://serverspec.org/resource_types.html#php_config) is useful. I would like to try and add it to Goss.  My question here is would that feature be accepted into the code here? I want to add it to Goss because we don't use ruby anywhere else so I have to install the language and a  bunch of extra dependencies just to get a simple feature from serverspec that goss doesn't have out of the box.  I prefer Goss because it is a simple binary and a simple config file and I am done.

Here is my current work around:

```
command:
  php -c /etc/php/7.0/apache2/php.ini -r "echo ini_get('memory_limit');":
    exit-status: 0
    stdout:
    - "256M"
  php -r "echo ini_get('opcache.enable');":
    exit-status: 0
    stdout:
    - "1"
```

but I would like the configuration to look more like:
```
php_config:
  memory_limit:
    value: "256M" #or pattern
    file: "/etc/php/7.0/apache2/php.ini"
  opcache.enable:
    value: "1" # or "On"
```

I would love to hear your thoughts. Just thought it might be nice to have php_config as a first class citizen. Just so you know I am new to Go so any code that I would write would probably need to be heavily reviewed.  If that is something that you think would be worth adding to Goss please let me know and I will gladly work on it, if not then we can close this.
