### ISSUE TITLE
Support for asserting against systemd template units?

### ISSUE THREAD

**Issue by petemounce** [aelsabbahy/goss#345]
I'm setting up some [buildkite agents](https://buildkite.com/docs/agent]). I'm running several instances per host, via their documentation.

I've got 8 running:

```
$ systemctl list-units | grep buildkite
buildkite-agent@1.service                                                                   loaded active running   Buildkite Agent
buildkite-agent@2.service                                                                   loaded active running   Buildkite Agent
buildkite-agent@3.service                                                                   loaded active running   Buildkite Agent
buildkite-agent@4.service                                                                   loaded active running   Buildkite Agent
buildkite-agent@5.service                                                                   loaded active running   Buildkite Agent
buildkite-agent@6.service                                                                   loaded active running   Buildkite Agent
buildkite-agent@7.service                                                                   loaded active running   Buildkite Agent
buildkite-agent@8.service                                                                   loaded active running   Buildkite Agent
system-buildkite\x2dagent.slice                                                             loaded active active    system-buildkite\x2dagent.slice
```

I've set up assertions as this, and they pass:

```yaml
service:
  buildkite-agent:
    enabled: false
    running: false
  buildkite-agent@1: # I'd like to ideally avoid duplicating this 8 times where only the index differs, since that will mean adjusting my tests if I change my mind about the number I want running. So I'd prefer this to be config/parameter-driven.
    enabled: true
    running: true
process:
  buildkite-agent:
    running: true
```

```shell
$ goss v -f tap
1..5
ok 1 - Process: buildkite-agent: running: matches expectation: [true]
ok 2 - Service: buildkite-agent@1: enabled: matches expectation: [true]
ok 3 - Service: buildkite-agent@1: running: matches expectation: [true]
ok 4 - Service: buildkite-agent: enabled: matches expectation: [false]
ok 5 - Service: buildkite-agent: running: matches expectation: [false]
```

I'd like to be able to make assertions like (as in, this is a sketch, I don't know whether it's a good one):

```yaml
process:
  buildkite-agent:
    running: true
    count: 8

service:
  buildkite-agent:
    enabled: true # when template, then I would expect this to pass only if all n are running
    running: true
    templated: true
    count: 8
```

I'd like to be able to supply the `count` as a parameter. Failing that, I'd like to template it in, somehow - I'm probably happy to do that externally rather than ask to complicate goss by building in templating, but I also don't know whether that's a reasonable thing to suggest or not.

What do you think?
