### ISSUE TITLE
Check if param is gt than

### ISSUE THREAD

**Issue by freeseacher** [aelsabbahy/goss#350]
I want to check if
```
kernel-param:
  net.core.somaxconn:
    value:
      gt: 5000
```
but got
```
F

Failures/Skipped:

net.core.somaxconn: value: Error: Expected a number.  Got:
    <string>: 10000
```

another try
```
command:
  sysctl -n net.core.somaxconn:
    exit-status: 0
    stdout:
      gt: 3000
    stderr: []
    timeout: 10000
```
gives 
```
Error: yaml: unmarshal errors:
  line 39: cannot unmarshal !!map into []string
```
docs was not helpfull.
