### ISSUE TITLE
Copy required files for a test to the system under test

### ISSUE THREAD

**Issue by d0x** [aelsabbahy/goss#356]
Is it possible to copy files to the system under test?

I like to test wether a cli-tool behaves correct. For that I added the following command:

```
command:
  # Test ImageMagick
  convert *.{png,jpeg,jpg} -quality 100 output.pdf:
      meta:
        desc: ImageMagick Test
      exit-status: 0
      stdout: []
      stderr: []
      timeout: 1000
```

But I need to put some test files to execute the `convert` command successfully. #
