### ISSUE TITLE
For service make one of enabled or running required

### ISSUE THREAD

**Issue by smutel** [aelsabbahy/goss#379]
Hello,

Currently to check the state of a service, parameters enabled AND running are required.
It would be better if only one of them is required.
This feature could be used to test system images during the creation process (packer) where services are enabled but not started yet.

Valid syntax should be one of:
```
service:
  sshd:
    enabled: true
```
or
```
service:
  sshd:
    running: true
```
or
```
service:
  sshd:
    enabled: true
    running: true
```

Thanks.
