### ISSUE TITLE
Is it possible to define sub templates?

### ISSUE THREAD

**Issue by Marcel-Lambacher** [aelsabbahy/goss#381]
Hi there,

is there a feature we're you can include sub templates?
I'm a really big fan of separation of concern and would like to separate each "validation group" into an own file.
Those sub templates should be defined in the master template which will be used from goss.

I'm imagining something like this:

- validate-master.yaml
- validate-ssh.yaml
- validate-kubernetes.yaml
- validate-other-stuff.yaml

And those sub templates can be defined in the master template like this:
```yaml
$ cat validate-master.yaml
sub-template:
  path: /path/to/validate-ssh.yaml
sub-template:
  path: /path/to/validate-kubernetes.yaml
sub-template:
  path: /path/to/validate-other-stuff.yaml
```
Is this somehow possible and if not, would you like to see such a feature? I would love to integrate it.

Best regards

Marcel Lambacher
