### ISSUE TITLE
Http check: headers options

### ISSUE THREAD

**Issue by byrnedo** [aelsabbahy/goss#387]
Would be nice to be able to check headers in http response, like:

```yaml
http:
    http://foo.bar
        headers: 
            Content-Type: application/json
```
