### ISSUE TITLE
Flag for deep merging gossfiles?

### ISSUE THREAD

**Issue by cheahjs** [aelsabbahy/goss#392]
I'm trying to do perform tests on the same resource in multiple goss files like so:

main.yaml:
```yaml
---
gossfile:
  - 1.yaml
  - 2.yaml
```

1.yaml:
```yaml
---
file:
  /var/lib/buildkite-agent/.ssh/known_hosts:
    contains:
      - github.com
```

2.yaml:
```yaml
---
file:
  /var/lib/buildkite-agent/.ssh/known_hosts:
    contains:
      - bitbucket.com
```

and I would have expected both tests to run:

```yaml
---
file:
  /var/lib/buildkite-agent/.ssh/known_hosts:
    contains:
      - github.com
      - bitbucket.com
```

but because of how `mergeGoss` is implemented (and is expected behaviour #150), only one of the tests will run and the other will be masked:

`goss render`:
```yaml
---
file:
  /var/lib/buildkite-agent/.ssh/known_hosts:
    contains:
      - bitbucket.com
```

It would be nice to have a flag to either perform a deep merge of the goss files, or maybe the ability to specify multiple goss files as a flag? The main motivation is to avoid having to run multiple instances of `goss serve` just to avoid the masking behaviour.
