### ISSUE TITLE
Add DNS check if IPs are valid

### ISSUE THREAD

**Issue by marcinpraczko** [aelsabbahy/goss#409]
I just disovered that Goss is not having any options to discover whether IPs are valid in DNS check. 

Scenario which I would expect goss have extra checks:
Lets say that there is domain 'domain.zone' and is configured to have three A records (1.1.1.1, 1.1.1.2, 1.1.1.3).
Goss checks looks like this (and this is working):
```yaml
dns:
  domain.zone:
    resolvable: true
    addrs:
      - 1.1.1.1
      - 1.1.1.2
      - 1.1.1.3
```

However if new IP is added to this pool - goss will still show everything as OK / Passed. What would be nice to have optional argument to check if there is no additinal IPs (for example 'expect_the_same: true'). 

From my point of view this is very valuable in terms of deteting issues with dynamically adjusted DNS and prevent for spoofing DNS. For example somebody added malisious IP to DNS records. So traffic still going to legitimate IPs - but from time to time is going to 'extra IP' which is not legitimate. 
This way goss can help detect this change really quickly.

**Comment by aelsabbahy** [comment]
`consist-of` is what you can use to accomplish this, see the gomega docs here for details: https://onsi.github.io/gomega/#consistofelement-interface

```yaml
dns:
  amazon.com:
    resolvable: true
    addrs:
    - 176.32.103.205
    - 176.32.98.166
    - 205.251.242.103
    timeout: 500
```

```yaml
dns:
  amazon.com:
    resolvable: true
    addrs:
      consist-of:
        - 176.32.103.205
        - 176.32.98.166
    timeout: 500
```
output:
```
.F

Failures/Skipped:

DNS: amazon.com: addrs:
Expected
    <[]string | len:3, cap:3>: ["176.32.103.205", "176.32.98.166", "205.251.242.103"]
to consist of
    <[]interface {} | len:2, cap:2>: [
        {
            Expected: "176.32.103.205",
        },
        {
            Expected: "176.32.98.166",
        },
    ]

Total Duration: 0.016s
Count: 2, Failed: 1, Skipped: 0
```

Feel free to open a new issue or comment on here if this isn't resolved for you.
