### ISSUE TITLE
in range can't get .Vars value

### ISSUE THREAD

**Issue by stefanmonkey** [aelsabbahy/goss#418]
```bash
goss --vars common.yaml -g test.yaml validate --format tap
```
respond with "2019/01/16 13:38:55 template: test:82:10: executing "test" at <.Vars.prefix_path>: can't evaluate field Vars in type interface {}"

test.yaml:
```yaml
file:
  # prometheus rules files
  {{ range .Vars.prometheus.rulefile }}
  {{ .Vars.prefix_path }}/rules/{{.}}:
    filetype: file
    exists: true
    mode: "0755"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ end }}
```

common.yaml:
```yaml
##
# common info
##
user_uid     :    1122
group_gid    :    1122
username     :    "prometheus"
groupname    :    "prometheus"

work_dir     :    /opt/tools/prometheus
prefix_path  :    /home/cmpt/prometheus

##
# prometheus info
##
prometheus:
  name: prometheus
  version: 2.3.2.linux-amd64
  port: 9090
  data_path: /home/prometheus/data
  config_file: prometheus.yml
  rulefile:
    - node_basic_rules.yml
```

**Comment by stefanmonkey** [comment]
```yaml
file:
  {{ $var := .Vars }}
  {{- range .Vars.prometheus.rulefile }}
  {{ $var.prefix_path }}/rules/{{.}}:
    filetype: file
    exists: true
    mode: "0755"
    owner: {{ $var.username }}
    group: {{ $var.groupname }}
  {{ end }}
``` 
worked!
https://medium.com/@IndianGuru/understanding-go-s-template-package-c5307758fab0 inspire me

**Comment by stefanmonkey** [comment]
A new issue:
only in `range file` can render  test.yaml:
```yaml
file:
  ## install path
  {{ .Vars.work_dir }}:
    filetype: directory
    exists: true
    mode: "0755"
    owner: root
    group: root

file:
  {{ .Vars.work_dir }}/{{ .Vars.prometheus.name }}-{{ .Vars.prometheus.version }}.tar.gz:
    filetype: file
    exists: true
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}:
    filetype: directory
    exists: true
    mode: "0755"
    owner: root
    group: root
  {{ .Vars.prefix_path }}/bin:
    filetype: symlink
    linked-to: {{ .Vars.work_dir }}/{{ .Vars.prometheus.name }}-{{ .Vars.prometheus.version }}
    exists: true
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}/etc:
    filetype: directory
    exists: true
    mode: "0755"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}/etc/{{ .Vars.prometheus.config_file }}:
    filetype: file
    exists: true
    mode: "0644"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prometheus.data_path }}:
    filetype: directory
    exists: true
    mode: "0754"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}/rules:
    filetype: directory
    exists: true
    mode: "0755"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  /lib/systemd/system/{{ .Vars.prometheus.name }}.service:
    filetype: file
    exists: true
    mode: "0644"
    owner: root
    group: root

file:
  {{ $var := .Vars }}
  {{- range .Vars.prometheus.rulefile }}
  {{ $var.prefix_path }}/rules/{{.}}:
    filetype: file
    exists: true
    mode: "0644"
    owner: {{ $var.username }}
    group: {{ $var.groupname }}
  {{ end }}
``` 

but range put top on all file, can render all
```yaml

file:
  {{ $var := .Vars }}
  {{- range .Vars.prometheus.rulefile }}
  {{ $var.prefix_path }}/rules/{{.}}:
    filetype: file
    exists: true
    mode: "0644"
    owner: {{ $var.username }}
    group: {{ $var.groupname }}
  {{ end }}

file:
  ## install path
  {{ .Vars.work_dir }}:
    filetype: directory
    exists: true
    mode: "0755"
    owner: root
    group: root

file:
  {{ .Vars.work_dir }}/{{ .Vars.prometheus.name }}-{{ .Vars.prometheus.version }}.tar.gz:
    filetype: file
    exists: true
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}:
    filetype: directory
    exists: true
    mode: "0755"
    owner: root
    group: root
  {{ .Vars.prefix_path }}/bin:
    filetype: symlink
    linked-to: {{ .Vars.work_dir }}/{{ .Vars.prometheus.name }}-{{ .Vars.prometheus.version }}
    exists: true
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}/etc:
    filetype: directory
    exists: true
    mode: "0755"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}/etc/{{ .Vars.prometheus.config_file }}:
    filetype: file
    exists: true
    mode: "0644"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prometheus.data_path }}:
    filetype: directory
    exists: true
    mode: "0754"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  {{ .Vars.prefix_path }}/rules:
    filetype: directory
    exists: true
    mode: "0755"
    owner: {{ .Vars.username }}
    group: {{ .Vars.groupname }}
  /lib/systemd/system/{{ .Vars.prometheus.name }}.service:
    filetype: file
    exists: true
    mode: "0644"
    owner: root
    group: root
```
