### ISSUE TITLE
Can not validate with go template in command arguments

### ISSUE THREAD

**Issue by lotusirous** [aelsabbahy/goss#423]
The following is the command for check local registry port on docker daemon.

```
$ goss add command 'docker info --format "{{ .RegistryConfig.IndexConfigs}}" |grep 3232 > /dev/null'
Adding Command to './goss.yaml':

docker info --format "{{ .RegistryConfig.IndexConfigs}}" |grep 3232 > /dev/null:
  exit-status: 1
  stdout: []
  stderr: []
  timeout: 10000
```

goss creates `goss.yaml`

```yaml
command:
  docker info --format "{{ .RegistryConfig.IndexConfigs}}" |grep 3232 > /dev/null:
    exit-status: 1
    stdout: []
    stderr: []
    timeout: 10000
```

Then `goss v` result as follows:

```
$ goss v
2019/02/22 03:05:46 template: test:2:42: executing "test" at <.RegistryConfig.Inde...>: can't evaluate field RegistryConfig in type *goss.TmplVars
```

**Comment by ryysud** [comment]
I also faced the same problem.

**Comment by elliotweiser** [comment]
Can confirm. Also applies to checking for IPs that listening ports bind to.

**Comment by elliotweiser** [comment]
In my case, `goss render` and `goss validate` yield:

```
executing "test" at <.Env.NGINX_BIND_IP>: can't evaluate field Env in type interface {}
```

**Comment by aelsabbahy** [comment]
Since the yaml file is parsed as a go-template, you would have to escape the curly braces
https://stackoverflow.com/a/17642427

Example:
```yaml
command:
  echo "{{`{{`}}foo{{`}}`}}":
    exit-status: 0
    timeout: 10000
```

Or the whole line can be escaped for easier readability:
```
command:
  {{`echo "{{foo}}" | tee wtf.log`}}:
    exit-status: 0
    timeout: 10000
```
or using double quotes.
```
command:
  {{"echo \"{{foo}}\""}}:
    exit-status: 0
    timeout: 10000
```

Any valid golang template escapes should work.

@elliotweiser can you post a snippet of the resource that was causing you issues?
