### ISSUE TITLE
Goss reporting randomly error: Client.Timeout exceeded

### ISSUE THREAD

**Issue by marcinpraczko** [aelsabbahy/goss#425]
Hi

I am having error related with timeout (this can be caused by our network - not sure). However what is strage is that I see following error quite frequently:

```
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

This is really random. Goss is running under docker (Alpine Linux).
I tried increase timeout configuration up to 5 secs in goss.yaml - however this is not helping at all.

```
dns:
  "hostname.local":
    resolvable: true
    timeout: 5000
    addrs:
      - 111.111.111.111
```

However when running goss - is not waiting for 5secs - only report error almost imidietly.
```GOSS CRITICAL - Count: 14, Failed: 2, Skipped: 2, Duration: 2.005s   # <--- Not 5 secs```

Any idea how to track whether goss is using provided timeout?
Is there any way to debug what goss is doing and what is real time out / error / etc?
