### ISSUE TITLE
dgoss creates world-writable directory

### ISSUE THREAD

**Issue by conn** [aelsabbahy/goss#426]
I've ran into a weird bug where a specific test executes differently when ran with `dgoss`.

Here's my `goss.yaml`:
```yaml
command:
    echo -n:
        exit-status: 0
        stdout: ['!']
        stderr: ['!']

    echo -n | grep nonexistent:
        exit-status: 1
        stdout: ['!']
        stderr: ['!']

    find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp:
        exit-status: 1
        stdout: ['!']
        stderr: ['!']
```

When running with `goss`:
`docker run -it -v "$GOSS_PATH":/goss:z -v "$(pwd)/goss.yaml":/goss.yaml:z debian:stable sh -c "/goss -g /goss.yaml validate --color --format documentation"`

```text
Command: echo -n: exit-status: matches expectation: [0]
Command: echo -n: stdout: matches expectation: [!]
Command: echo -n: stderr: matches expectation: [!]
Command: echo -n | grep nonexistent: exit-status: matches expectation: [1]
Command: echo -n | grep nonexistent: stdout: matches expectation: [!]
Command: echo -n | grep nonexistent: stderr: matches expectation: [!]
Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: exit-status: matches expectation: [1]
Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: stdout: matches expectation: [!]
Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: stderr: matches expectation: [!]


Total Duration: 0.029s
Count: 9, Failed: 0, Skipped: 0
```

When running with `dgoss`:
`dgoss run -it --rm debian:stable`

```text
INFO: Starting docker container
INFO: Container ID: 7a15af29
INFO: Sleeping for 0.2
INFO: Container health
PID                 USER                TIME                COMMAND
13412               root                0:00                bash
INFO: Running Tests
Command: echo -n: exit-status: matches expectation: [0]
Command: echo -n: stdout: matches expectation: [!]
Command: echo -n: stderr: matches expectation: [!]
Command: echo -n | grep nonexistent: exit-status: matches expectation: [1]
Command: echo -n | grep nonexistent: stdout: matches expectation: [!]
Command: echo -n | grep nonexistent: stderr: matches expectation: [!]
Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: exit-status:
Expected
    <int>: 0
to equal
    <int>: 1
Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: stdout: patterns not found: [!]
Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: stderr: matches expectation: [!]


Failures/Skipped:

Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: exit-status:
Expected
    <int>: 0
to equal
    <int>: 1
Command: find / -xdev \( -type f -o -type d \) -perm -0002 | grep --invert-match --regexp ^/tmp --regexp ^/run/lock --regexp ^/var/tmp: stdout: patterns not found: [!]

Total Duration: 0.028s
Count: 9, Failed: 2, Skipped: 0
INFO: Deleting container
```

Can someone please reproduce this bug?
