### ISSUE TITLE
Feature: check for 'apt-key list' contains only expected keys

### ISSUE THREAD

**Issue by sergiik** [aelsabbahy/goss#43]
Hi,

It would be nice to have some special check for apt keys to make sure nothing is missed and nothing extra is there. Right now the only way I see how to do it is to use command check for apt-key but it's not convenient and reliable way as the order/description of keys can  be changed. Also it very hard to template such check. What do you think about such feature? May be even with current functionality there is a way to simplify such checks? 

--
thanks,
sergii

**Comment by aelsabbahy** [comment]
Not pretty, but easiest for now would probably be:

```
# apt-key list
/etc/apt/trusted.gpg
--------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>
```

A test could be like:
```yaml
command:
  apt-key adv --list-public-keys --with-colons | grep '^pub' | cut -d':' -f 5 | egrep -o '.{8}$':
    exit-status: 0
    stdout:
    - 437D05B5
    - C0B21F32
    - EFE21092
    - FBB75451
    stderr: []
    timeout: 10000
  apt-key adv --list-public-keys --with-colons | grep -c '^pub':
    exit-status: 0
    stdout:
    - "4"
    timeout: 10000
```

You can skip the `| egrep...` if you don't mind matching the full key-ID, I only did it to more closely match the output of `apt-key list`. Order shouldn't matter in this case, the test will succeed regardless of order, so long as the string is present

I've been very hesitant to include os/tool-specific tests into goss, the trick for me is finding the balance between what to support, and what to push down into `command`

Is the above sufficient for your needs?
