### ISSUE TITLE
Goss should provide the ability to inspect kernel modules loaded

### ISSUE THREAD

**Issue by videte47** [aelsabbahy/goss#430]
I would like to inspect the loaded modules on the target system. Basically go though the same motions that `lsmod` does to infer if a given kernel module is loaded

**Comment by aelsabbahy** [comment]
Command + `lsmod`/`modinfo` should cover most if not all use cases for now, example:
```
command:
  lsmod:
    exit-status: 0
    stdout:
    - vboxpci
    - vboxdrv
    - '!foobar'
    stderr: []
    timeout: 10000
```
