### ISSUE TITLE
service check definitions should make 'enabled' as an optional attribute

### ISSUE THREAD

**Issue by sshipway** [aelsabbahy/goss#432]
A service check definition requires the 'running' and 'enabled' attributes to be set.  However the 'enabled' should be optional as we may with to only validate that the service is running, not how it was started (if, for example, a nonstandard service management framework is being used)

**Comment by sshipway** [comment]
In this pull request: https://github.com/aelsabbahy/goss/pull/434

**Comment by sshipway** [comment]
As a workaround for this, you can use a matcher --
```
service:
  foo:
    running: true
    enabled:
      or:
        - true
        - false
```

This effectively makes the 'enabled' check a null operation and so only checks the running state.

**Comment by aelsabbahy** [comment]
Clever workaround. Might be a nice note in the documentation.

**Comment by aelsabbahy** [comment]
Marking this as approved for the documentation change.

@sshipway let me know if you feel strongly about this needing to be supported outside of the workaround.

I'd have to delve into the code a bit more.. but I remember there was a reason why the check couldn't be optional.

**Comment by freeseacher** [comment]
Yep. got almost the same issue. 
but i want to test only if nginx is enabled. no matter if it running or not

// i want to test if my packer image was build well. so actual service run is not really matters

**Comment by sshipway** [comment]
@freeseacher just use this:

```
service:
  nginx:
    running:
      or:
        - true
        - false
    enabled: true
```
