### ISSUE TITLE
package version checks should allow ranges (Feature request)

### ISSUE THREAD

**Issue by sshipway** [aelsabbahy/goss#435]
When specifying a required package version, it should be possible to use ranges (> or < ).  This would allow a test for 'at least this version' (to avoid a known bug) or 'no later than this version' (to avoid incompatibilities).  Ideally, the syntax could also allow 'or not installed' as an extension to this.

May be related to #355

**Comment by aelsabbahy** [comment]
It's somewhat related to #355, semver is a check I would like to add as an [advanced macher](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#advanced-matchers)

However, each package manager uses its own way to compare versions, so that may or may not be helpful depending on the package manager and it's comparison rules.

For example RPM uses the following logic to compare versions:
https://blog.jasonantman.com/2014/07/how-yum-and-rpm-compare-versions/

**Comment by thatsk** [comment]
for Rpm based:-
you should be do 
   cmd := util.NewCommand("rpm", "-q", "--nosignature", "--nohdrchk", "--nodigest", "--qf", "%{VERSION}-%{RELEASE}.%{ARCH}\n", p.name)

**Comment by pedroMMM** [comment]
#508 should take care of this.

Simple check `x > 4.0.0`:
```yaml
package:
  kernel:
    installed: true
    versions:
      version-gt: "4.0.0"
```

Range check `5.0.0 < x > 4.0.0`:
```yaml
package:
  kernel:
    installed: true
    versions:
      and:
      - version-gt: 4.0.0
      - version-lt: 5.0.0
```
