### ISSUE TITLE
Create `meta` attribute

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#44]
#Resources should be able to define a `meta` attribute, that is an unopinionated object of string-key + any value pairs. Rename `desc` to `title`.

Example:
```yaml
users:
  nobody:
    title: This is the nobody test
    meta:
      desc: ensure nobody exists as per our standard
      severity: 5
    exists: true
```

For now this should be exposed by the JSON output format in the test result, ex:
```json
{
    "results": [
        {
            "duration": 102152,
            "err": null,
            "expected": [
                "true"
            ],
            "found": [
                "true"
            ],
            "human": "",
            "meta": {
                "desc": "ensure nobody exists as per our standard",
                "severity": 5
            },
            "property": "exists",
            "resource-id": "nobody",
            "resource-type": "User",
            "successful": true,
            "summary-line": "User: nobody: exists: matches expectation: [true]",
            "test-type": 0,
            "title": "This is the nobody test"
        }
    ],
    "summary": {
        "failed-count": 0,
        "summary-line": "Count: 1, Failed: 0, Duration: 0.003s",
        "test-count": 1,
        "total-duration": 3492688
    }
}
```
