### ISSUE TITLE
Ulimit check doesn't appear to work

### ISSUE THREAD

**Issue by asciifaceman** [aelsabbahy/goss#450]
```
vagrant@devel:~$ ulimit -Sn
65535
vagrant@devel:~$ ulimit -Hn
65535
```

```
command:
  ulimitHard:
    exit-status: 0
    exec: "ulimit -Hn"
    stdout:
      - 65535

  ulimitSoft:
    exit-status: 0
    exec: "ulimit -Sn"
    stdout:
      - 65535
```

Expected result: passes

Result:
`Command: ulimitSoft: ulimit -Sn: stdout: patterns not found: [65535]`

`Command: ulimitHard: ulimit -Hn: stdout: patterns not found: [65535]`

Note: I have also tried wrapping it as a string instead of an integer.

**Comment by asciifaceman** [comment]
I haven't been able to figure out if this is an issue with goss or how `ulimit` reports to stdout

**Comment by aelsabbahy** [comment]
What does `goss add command 'ulimit -Sn'` say?

**Comment by asciifaceman** [comment]
```
vagrant@devel:~$ goss add command 'ulimit -Hn'
Adding Command to './goss.yaml':

ulimit -Hn:
  exit-status: 0
  stdout:
  - "65535"
  stderr: []
  timeout: 10000


vagrant@devel:~$ goss add command 'ulimit -Sn'
Adding Command to './goss.yaml':

ulimit -Sn:
  exit-status: 0
  stdout:
  - "65535"
  stderr: []
  timeout: 10000
```

Interesting it is in a different format from the documentation.

```
vagrant@devel:~$ goss validate
......

Total Duration: 0.006s
Count: 6, Failed: 0, Skipped: 0
```

**Comment by aelsabbahy** [comment]
Try the original with quotes around the number. Sorry, I'm not on a computer to test it currently.

```
command:
  ulimitHard:
    exit-status: 0
    exec: "ulimit -Hn"
    stdout:
      - "65535"
```

**Comment by asciifaceman** [comment]
I had done quotes around the number originally as well and had the same behavior.

**Comment by asciifaceman** [comment]
However part of this problem appears to be in the ansible wrapper project I"m using which I've opened an issue against there.

I'll try to test the original again with raw goss in a few.

**Comment by aelsabbahy** [comment]
I'm not able to reproduce this locally:
```
command:
  ulimit -Hn:
    exit-status: 0
    stdout:
    - "4096"
    stderr: []
    timeout: 10000
  ulimit-check:
    exec: "ulimit -Hn"
    exit-status: 0
    stdout:
    - "4096"
    stderr: []
    timeout: 10000
```

This goss file tests both cases and they both pass for me. Are you still having this issue?
