### ISSUE TITLE
Commands are not executed in the order they defined

### ISSUE THREAD

**Issue by Mad-ness** [aelsabbahy/goss#455]
Hi,

I've two ideas.

1) I'd like to define multiple commands in goss.yml and I expect they are being run in the same order as they go in the file. But they do not run in the same order, sometimes they do. It looks like they run randomly. 
Example of commands:
- mount a NFS share
- check permissions
- unmount the share.

It would be great if it possible to define either order of execution (maybe add an option "priority") or just follow the order the commands are defined in goss.yml.

2) I feel a big inconvenience in running multiple commands using "command" test. It would be awesome to have a test called **script** where I can specify a code of a multiline script. This might look like this:

```
script:
  myscript:
    body: |
      #!/bin/bash, #!/usr/bin/env python, #!/usr/bin/awk, #!/usr/bin/sed, etc
      as many as need shell/python/awk/etc commands or other script language instructions
      on many lines
   exit-status: 
   stdout: []
  ... etc ...
```
I know I can put needed scripts on a target host/image and execute it using **command** but the powerfull side of Goss is a simplicity. I wouldn't like to split a simple configuration into multiple pieces.

Thanks,
Dmitrii

**Comment by sshipway** [comment]
This is related to my #485 feature request, to add before/after attributes to tests to enforce ordering

Normally all tests run in parallel...

**Comment by aelsabbahy** [comment]
1. Tests being independent allows for a lot of flexibility for execution order and in my opinion improves predictability. Ordering is not something I want to add to goss.

2. The PR that @sshipway introduced a while back will allow some limited support for the simple use-case you want, example:
```yaml
command:
  python_example:
    exec: |
      python3 << EOF
      import sys
      print('example output')
      for i in range(3):
        print(i)
      sys.exit(15)
      EOF
    stdout:
      - 'example'
      - '0'
      - '1'
      - '2'
    exit-status: 15
    timeout: 10000
```

```
goss v
..

Total Duration: 0.031s
Count: 2, Failed: 0, Skipped: 0
```

I know it's not the most ideal syntax, but.. putting code in yaml is less than ideal.

That said, in its current state it butchers the output when using more verbose formatters. I have a PR open https://github.com/aelsabbahy/goss/pull/495 but will wait on @sshipway to understand the rationale behind the original change better.

@Mad-ness Does this meet your needs?
