### ISSUE TITLE
command execution fails

### ISSUE THREAD

**Issue by pimperator** [aelsabbahy/goss#469]
Hi Guys,

I am having this kind of command definition
```
command:
  runner_privileged:
    title: checking for return code 0
    exec: "echo true"
    stdout:
      - /true$/
    exit-status: 0 
    stderr: []
    timeout: 1000
```
but sadly I recieve 
```
# goss -g check_running.yml validate
Error: Invalid Attribute for Command:runner_privileged: exec
```

so I need to switch to 
```
command:
  "echo true":
    title: checking for return code 0
    stdout:
      - /true$/
    exit-status: 0 
    stderr: []
    timeout: 1000
```

Did I misconfigure something or what am I doing wrong?
According on documentation https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#command 

> The exec attribute is the command to run; this defaults to the name of the hash for backwards compatibility

So what am I doing wrong?

P.S.: originally I wanted to do something like this:
```
  aws_s3_ls:
    title: check access on Cache-Bucket
    exec: 
      - export AWS_ACCESS_KEY_ID="$(grep "AccessKey" /etc/gitlab-runner/config.toml |cut -f 2 -d '=' |cut -f 2 -d '"')"
      - export AWS_SECRET_ACCESS_KEY="$(grep "SecretKey" /etc/gitlab-runner/config.toml |cut -f 2 -d '=' |cut -f 2 -d '"')"
      - export AWS_DEFAULT_REGION="$(grep "BucketLocation" /etc/gitlab-runner/config.toml |cut -f 2 -d '=' |cut -f 2 -d '"')"
      - aws s3 ls s3://$(grep "BucketName"  /etc/gitlab-runner/config.toml |cut -f 2 -d '=' |cut -f 2 -d '"')
    stdout:
      - /secretsecret/
    exit-status: 0 
    stderr: []
    timeout: 1000
```
