### ISSUE TITLE
Test precedence rules and sequencing of tests (feature request)

### ISSUE THREAD

**Issue by sshipway** [aelsabbahy/goss#485]
Currently, all tests are run in parallel, which is faster and efficient.  However, some tests may not be able to run in parallel with others, or may need to test output created by previous tests.

Can we add optional scheduling attributes 'before' and 'after' to indicate when a test should not be started until the (successful) completion of another test?

This might be a bit of a can-o-worms as it then requires checks for circular dependencies, and a method to start a new thread once its requirements are completed.

**Comment by aelsabbahy** [comment]
Can you give a real world example of this use case?

**Comment by sshipway** [comment]
On one system, I wanted to use Goss to test the application behaviour under tests which temporarily modify the database.  There are several tests to run, but unfortunately they cannot run simultaneously as they modify the same area of data, and so they have to run sequentially.

In the end, I was able to make some major changes to the unit tests so that they could run in parallel.  However it would have been easier had I been able to mark a dependency sequence to allow the tests to run consecutively.

**Comment by sshipway** [comment]
Another example would be a test that requires some separate test data to have been set up in advance.  One test could test for the existence of the test data, and another tests for the functionality.  For example, test that a certain DNS name is resolveable; if so, we can continue to test the function that depends on it.  This makes it easier to focus on the root cause of a failure.

It would be useful if a whole test could be Skipped if the dependent test failed, in much the same way that a command stdout pattern test is skipped when the exit-status test fails.

**Comment by aelsabbahy** [comment]
## First example:
1. I don't think goss should be in the business of changing system state, rather only testing it.
2. That said, if your tests cannot be run in parallel, this can be handled by using `goss v --max-concurrent 1`
For example:
```yaml
command:
  01:
    exec: sleep 1
    exit-status: 0
  02:
    exec: sleep 1
    exit-status: 0
  03:
    exec: sleep 1
    exit-status: 0
```
```
$ goss v
...

Total Duration: 1.008s
Count: 3, Failed: 0, Skipped: 0

$ goss v --max-concurrent 1
...

Total Duration: 3.010s
Count: 3, Failed: 0, Skipped: 0
```

Test order is not guaranteed and will be random, this can be observed by using `--format documentation`.

## Second example:
I do see some benefit of this to aid with root cause. However, it adds a lot of complexity to the task scheduler, and adds little to the user experience. Here's my high level thoughts on what would be needed and why I feel overall the cost/benefit of the effort might not be worthwhile:
1. Add dependency management.
2. Deduplication/locking of executors. Example: TaskA and TaskB depend on TaskC, only run/report C once.
3. Detection of circular dependencies.

or as you put it, it's a bit of "can-o-worms" =)

One possible alleviation of the clarity/root-cause problem would be leveraging the `meta` field, I know this isn't exactly what you're looking for, but it might help if you're not already leveraging them:
```yaml
dns:
  localhost2:
    resolveable: true
    timeout: 500
command:
  ping_google:
    # "title" and "meta" are arbitrary values that will be printed out in the test output.
    # "title" is a string value, "meta" is an arbitrary set of key/value pairs.
    # Here we are using meta to provide the user with checklist of possible remedies
    # when this test fails
    title: Check that we can ping google successfully
    meta:
      remedy.1: Check if DNS test failed first
      remedy.2: Check firewall rules
    exec: ping -c 1 -W 1 localhost2
    exit-status: 0
```

And the output:
```
$ goss v
FF

Failures/Skipped:

DNS: localhost2: resolvable:
Expected
    <bool>: false
to equal
    <bool>: true

Title: Check that we can ping localhost2 successfully
Meta:
    remedy.1: Check if DNS test failed first
    remedy.2: Check firewall rules
Command: ping_localhost2: exit-status:
Expected
    <int>: 2
to equal
    <int>: 0

Total Duration: 0.036s
Count: 2, Failed: 2, Skipped: 0
```
