### ISSUE TITLE
Add `title` and `meta` to rspecish and documentation output formats

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#52]
Add `title` and `meta` (when provided) to `rspecish` and `documentation` output formats, example:
```
Title: 3.9.4 Test if sshd is running
Meta:
    foo: bar moo cow
    sev: 5
Service: sshd: enabled: matches expectation: [true]
Service: sshd: running: matches expectation: [true]
```

@timstoop I'm hoping this can be useful for [cis-in-goss](https://github.com/timstoop/cis-in-goss)
