### ISSUE TITLE
IPv6 PTR  DNS record test

### ISSUE THREAD

**Issue by gsauthof** [aelsabbahy/goss#525]
**Describe the bug**

Goss doesn't support testing the PTR record for an IPv6 address.

See also: https://github.com/aelsabbahy/goss/issues/377#issuecomment-564911046

**How To Reproduce**

```
dns:
  PTR:2a00:1450:400c:c07::1a:
    server: 1.1.1.1
    resolvable: true
    addrs:
    - "wo-in-x1a.1e100.net."
```

**Expected Behavior**

no error, success/failure depending if it really resolves to the expected domain name specified under the `addrs:` key

**Actual Behavior**

```
PTR:2a00:1450:400c:c07::1a: resolvable: Error: dns: unrecognized address: 2a00
DNS: 2a00:1450:400c:c07::1ad: addrs: skipped
```

**Environment:**
 - Version of goss v0.3.6
 - OS/Distribution version (if applicable) CentOS 7
