### ISSUE TITLE
Allow users to overwrite default driver/type

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#539]
**Describe the feature:**

Currently goss decides which package manager and service manager to use based on your OS. This feature is to allow users to overwrite this.

**Describe the solution you'd like**

Open to suggestions on this, two possibilities I'm debating:
1) Use `PKG_TYPE:PACKAGE_NAME` syntax, this is consistent with the port checks.

Example:
```
package:
  rpm:coreutils:
    installed: true
    versions:
    - "8.27"
```

2) Create a new attribute to control this, example "type" or "'driver"

Example:
```
package:
  coreutils:
    type: rpm
    installed: true
    versions:
    - "8.27"
```
