### ISSUE TITLE
Bug: HTTP check fails when http content is too large with "Body: Error: bufio.Scanner: token too long"

### ISSUE THREAD

**Issue by rmetzler** [aelsabbahy/goss#580]
**Describe the bug**

I have some very big XMLs I need to verify
- the HTTP status code is 200
- it starts with the xml declaration
 
**How To Reproduce**

```
http:

  https://www.zdf.de/sitemap_0.xml:
    status: 200
    allow-insecure: false
    no-follow-redirects: false
    timeout: 5000

    # all documents should return XML with www.zdf.de in it
    body:
      - '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'

```

**Expected Behavior**

goss should say this is ok

**Actual Behavior**

```
$ goss -gossfile=src/goss/sitemap/bug.yaml v --format=documentation
HTTP: https://www.zdf.de/sitemap_0.xml: status: matches expectation: [200]
https://www.zdf.de/sitemap_0.xml: Body: Error: bufio.Scanner: token too long


Failures/Skipped:

https://www.zdf.de/sitemap_0.xml: Body: Error: bufio.Scanner: token too long

Total Duration: 0.582s
Count: 2, Failed: 1, Skipped: 0
```
**Environment:**
 - Version of goss: 7b6cd899d94b4f0857b5ff3289b5a8d26edf1b09
 - OS/Distribution version: I build and run on MacOS
