### ISSUE TITLE
How command option works?

### ISSUE THREAD

**Issue by BeamerIsHere** [aelsabbahy/goss#584]
Hi All,

I'm bit confused about command option, Is it just to check whether a command is there or not? or can I run some command during the testing using goss.yaml? 

My requirement is to test a command during the dgoss run process. 
Example :- I want to run a script inside the container using dgoss ( goss add command ./bashscript) while testing the container using dgoss run command. Is that possible.?

**Comment by aelsabbahy** [comment]
The command option runs the script and allows you to validate exit-status or output of the command:
https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#command

Example:
```yaml
command:
  echo hello world:
    exit-status: 0
    stdout:
    - hello world
    stderr: []
    timeout: 10000
```
