### ISSUE TITLE
Command has escaped unicode characters

### ISSUE THREAD

**Issue by EleanorRigby** [aelsabbahy/goss#604]
**Describe the bug**
The command fails to work as goss escapes some characters.

**How To Reproduce**
For instance, 
```
command:
  /opt/cni/bin/host-device 2>&1 | awk -F' ' '{print substr($4,2); }':
    exit-status: 0
    stdout: []
    stderr:
    - 0.8.6
    timeout: 0
```
The `2>&1` is crucial because the result is only printed to stderr which we want to check.

When I saw GOSS executing this, it fails 
```
{
            "duration": 7552,
            "err": null,
            "expected": [
                "0.8.6
            ],
            "found": null,
            "human": "",
            "meta": null,
            "property": "stderr",
            "resource-id": "/opt/cni/bin/host-device 2\u003e\u00261 | awk -F' ' '{print substr($4,2); }'",
            "resource-type": "Command",
            "result": 1,
            "successful": false,
            "summary-line": "Command: /opt/cni/bin/host-device 2\u003e\u00261 | awk -F' ' '{print substr($4,2); }': stderr: patterns not found: [0.8.6]",
            "test-type": 2,
            "title": ""
        },
```
The `2>&1` got changed to `2\u003e\u00261` which fails the redirection and there is nothing for awk pipe to do.

**Expected Behavior**
Expected this to not escape the `>` `&`

**Environment:**
 - Version of goss : 0.3.13
 - OS/Distribution Amazon Linux 2
