### ISSUE TITLE
Support dynamic ip address in interface test

### ISSUE THREAD

**Issue by tomoyk** [aelsabbahy/goss#630]
**Describe the feature:**

Currently, dynamic IP address testing is not supported in `interface` section. 

Please support CIDR-based IP address testing.

**Describe the solution you'd like**

Example format:

```
interface:
  eth0:
    # required attributes
    exists: true
    # optional attributes
    addrs-range:
    - 172.17.0.0/16
    - 10.0.0.0/8
    mtu: 1500
```

**Describe alternatives you've considered**

It can also be expressed in the `command` section.

```
command:
  ipaddr:
    exit-status: 0
    exec: 'ip -f inet -o addr show eth0 | grep -o inet 10.[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}"'
    timeout: 10000 # in milliseconds
    skip: false
```
