### ISSUE TITLE
Multiple variables in single test

### ISSUE THREAD

**Issue by vinodhkumart** [aelsabbahy/goss#654]
Hi , I am using puppet template to declare my variables. Now my puppet facts has the below key and value.

puppet fatcs:
-----------------
region: us
serverenv: dev

Now , I am planning to write a test that whenever my region and serverenv matches as uk,dev then the below file should  have this repository url configured.

But getting failed as I am not sure how can i provide multiple variables here.. Please suggest
goss test:
------------
  /etc/yum.repos.d/epel.repo:
    exists: true
    mode: "0644"
    owner: root
    group: root
    contains:
    {{if eq .Vars.region "uk"}} & {{if eq .Vars.serverenv "dev"}}  
    - "http://yumrepo.example.com/$releasever/repository/epel"
    {{end}}

Regards
Vinod

**Comment by vinodhkumart** [comment]
Does anyone has solution for this?

**Comment by wilrodriguez** [comment]
Good news, this actually isn't as hard to tackle as you'd think. The official golang docs are kinda terrrible, but other people on the internet have written pretty good tutorials. I found [this one](https://curtisvermeeren.github.io/2017/09/14/Golang-Templates-Cheatsheet) here that helped me answer this question for you.

This is what you're looking for:

```yaml
/etc/yum.repos.d/epel.repo:
exists: true
mode: "0644"
owner: root
group: root
contains:
{{if and (eq .Vars.region "uk") (eq .Vars.serverenv "dev")}}
- "http://yumrepo.example.com/$releasever/repository/epel"
{{end}}
```
