### ISSUE TITLE
Add sha512 support to file resource

### ISSUE THREAD

**Issue by jay7x** [aelsabbahy/goss#655]
**Describe the feature:**

I'd like to use sha512 checksums in tests in some cases. This is mainly based on some internal processes in my company.

**Describe the solution you'd like**

```yaml
file:
  /etc/passwd:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    sha512: cb71b1940dc879a3688bd502846bff6316dd537bbe917484964fe0f098e9245d80958258dc3bd6297bf42d5bd978cbe2c03d077d4ed45b2b1ed9cd831ceb1bd0
```
