### ISSUE TITLE
High CPU usage using port checking

### ISSUE THREAD

**Issue by nlamirault** [aelsabbahy/goss#682]
**Describe the bug**

We have a goss configuration with port 

```yaml
port:
  tcp:8080:
    listening: true
    ip:
    - 0.0.0.0
```

**How To Reproduce**

**Expected Behavior**

**Actual Behavior**

Goss was on the VM the process that consumed the most CPU
Goss seems to list all open ports in order to find out which one we define is open or not.

**Environment:**
 - Version of goss : v0.3.16
 - OS/Distribution version (if applicable) : Debian
