### ISSUE TITLE
how to add complexe command below ?

### ISSUE THREAD

**Issue by spham** [aelsabbahy/goss#710]
hi
i wish to add command below but have error

```
goss add command `erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell`
```

instead of 

    stderr: 23.3.4.4

i have 

```
  exit-status: 127
  stdout: []
  stderr:
  - 'sh: 23.3.4.4 : commande introuvable'
  timeout: 10000
```
