### ISSUE TITLE
Dgoss ASP.NET Image Test failed

### ISSUE THREAD

**Issue by SmnHgr** [aelsabbahy/goss#721]
Why does dgoss not work with this ASP.NET container template?

[Used docker image](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-5.0)

I've build the image and tested dgoss on a linux distribution (fedora).

goss.yaml
```
port:
  tcp:80:
    listening: true
    ip:
      - 0.0.0.0

http:
  http://localhost:80:
    status: 200
    timeout: 5000
    body: []
```
Output
![image](https://user-images.githubusercontent.com/27735362/137674306-3640a83b-b8fe-4fca-acef-7a7534d9f8b7.png)
