### ISSUE TITLE
How to ensure SSH doesn't listen all IPs/interfaces

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#85]
Is it possible to ensure SSH doesn't listen all IPs/interfaces? Something like this: 

```
        "tcp:22": {
            "listening": true,
            "ip": [
                "127.0.0.1",
                "10.0.0.1"
            ]
        },
        "tcp:22": {
            "listening": false,
            "ip": [
                "0.0.0.0"
            ]
        },
```

As I can see here https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#port---add-a-port
'listening=false' doesn't care about 'ip' value. My results for the example above is:

```
Failures:
Port: tcp:22: listening: doesn't match, expect: [false] found: [true]
Port: tcp:22: ip: expectations not found [0.0.0.0]

netstat -anp | grep 22
tcp        0      0  127.0.0.1:22            0.0.0.0:*               LISTEN      -               
tcp        0      0  10.0.0.1:22             0.0.0.0:*               LISTEN      - 
```

Tnx!

**Comment by aelsabbahy** [comment]
This can be done with [advanced matchers](https://github.com/aelsabbahy/goss/blob/master/docs/manual.md#advanced-matchers)

There are different ways to approach this.
Exact match:
```yaml
port:
  tcp:22:
    listening: true
    ip:
      consist-of:
        - 127.0.0.1
        - 10.0.0.1
```

If you just want to make sure `0.0.0.0` isn't listening, but don't care about what is:
```yaml
port:
  tcp:22:
    listening: true
    ip:
      not:
        contain-element: 0.0.0.0
```

You can get more complex with `and` and `or` operators as needed.
